= User Profile Sample: Couchbase Lite Fundamentals

== Introduction
Couchbase Mobile brings the power of NoSQL to the edge. It is comprised of three components:

. *Couchbase Lite*, an embedded NoSQL JSON Document Style database for your mobile apps.
. *Sync Gateway*, an internet-facing synchronization mechanism that securely syncs data between mobile clients and servers.
. *Couchbase Server*, a highly scalable, distributed NoSQL database platform.

Couchbase Mobile supports flexible deployment models. You can deploy

* Couchbase Lite as a standalone embedded database within your mobile apps or,
* Couchbase Lite enabled mobile clients with a Sync Gateway to synchronize data between your mobile clients or,
* Couchbase Lite enabled clients with Sync Gateway to sync data between mobile clients and the Couchbase Server, which can persist data in the cloud (public or private).

This tutorial will walk you through a very basic example of how you can use *Couchbase Lite 2.x in standalone mode* within your Flutter app for iOS and Android.

You will learn the fundamentals of

* Database operations
* Document CRUD Operations

====
You can learn more about Couchbase Mobile link:https://developer.couchbase.com/mobile/[here]
====

== Prerequisites
This tutorial assumes familiarity with building link:https://flutter.dev/[Flutter] apps using Dart.

* iOS (9+)
* Android (SDK 19+)

== App Overview
In this tutorial you will be working with an app that allows users to log in and make changes to their user profile information.

User profile information is persisted as a `Document` in the local Couchbase Lite `Database`. When the user logs out and logs back in again, the profile information is loaded from the `Database`.

== Installation
=== Fetching App Source Code
==== Option 1 : Git Clone

* Clone the *standalone* branch of the `User Profile Demo` solution from GitHub. Assuming you have link:https://git-scm.com/downloads[Git] installed you can use the following command to clone the solution:

[source, bash]
----
git clone -b standalone https://github.com/fluttercouch/userprofile-couchbase.mobile-flutter.git
----

==== Option 2: Download .zip
* Download the `User Profile Demo` solution directly from link:https://github.com/fluttercouch/userprofile-couchbase-mobile-flutter/archive/standalone.zip[here]


Once all of the solution bits have been retrieved you can verify the installation, and run the app!

=== Try it out
* Start _Android Studio_, select _Open a existing Android Studio project_ and navigate to the main project directory.
* Start your preferred simulator or attach you device. For simulators you can choose between iOS Simulator (only if you are running MacOS) and Android simulator in the toolbar.
* Run the app selecting _Run 'main.dart'_ from the _Run_ menu.
* Verify that you see the login screen.

== Project overview
The User Profile demo app is a Flutter project that supports iOS and Android.

The project is divided in several directory:

* *android/* : it contains Android relative code. You can open this directory directly in Android Studio and modify Android relative options such as build.gradle and AndroidManifest.xml files.
* *assets/* : it contains images and static files that will be bundle with the app.
* *build/* : this directory is created after your first build and it contains the results of the build process.
* *ios/* : it contains iOS relative code. You can open this directory directly in XCode and modify iOS relative options such as the Info.plist file, or the options of the package in the Runner section.
* *lib/* : it contains all the Dart code of your project. It is where your Flutter code lives!
* *pubspec.yaml*: it's the configuration file of the Flutter project. In here you can declare the project name, your dependecies and your assets.

== Getting started with Couchbase Lite
In order to use Couchbase Lite within a Flutter app you have to declare Fluttercouch as a dependency in your project. You have to edit your `pubspec.yaml` so that it seems like this, and then run `flutter packages get` in a terminal within the main project directory.

[source, yaml]
----
dependencies:
  flutter:
    sdk: flutter
  fluttercouch: ^1.0.0
----

Now that the `Fluttercouch` library has been imported in your project, you are ready to start taking advantage of a variety of features. However, before diving into the capabilities offered though `Fluttercouch` let's take a look at the foundations of Couchbase: data models and documents.

== Data Model
Couchbase Lite is a JSON Document Store. A `Document` is a logical collection of named fields and values. The values are any valid JSON types. While it is not required or enforced, it is a recommended practice to include a _"type"_ property that can serve as a namespace for related documents.

=== The "User Profile" Document
The app deals with a single `Document` with a _"type"_ property of _"user"_. The document ID is of the form _"user::<email>"_. An example of a document would be

[source, json]
----
{
    "type":"user",
    "name":"Jane Doe",
    "email":"jane.doe@earth.org",
    "address":"101 Main Street"
}
----

=== User Profile
The _"user"_ `Document` is encoded to a class named _UserProfile_ that resides in the _lib/models/user_profile.dart_ file.

[source, dart]
----
class UserProfile {
  final String id;
  final String name;
  final String email;
  final String address;
  final String description;

  UserProfile({this.id, this.name, this.email, this.address, this.description});
}
----

== Basic Database Operations
In this section, we will do a code walkthrough of the basic Database operations.

=== Create / Open a Database
When a user logs in, we create an empty Couchbase Lite database for the user if one does not exists.

* Open the my_model.dart file in _lib/_ and locate the `MyModel` class. In order to use it as a Fluttercouch feature provider you have to extend it with the Fluttercouch mix-in.

[source, dart]
----
import 'package:fluttercouch/fluttercouch.dart';  # <1>

class MyModel extends Object with Fluttercouch { # <2>

  MyModel() {
    
  }

}
----
<1> Import the library poiting to _fluttercouch.dart_ file: Dart will import automatically every parts of the library for you.
<2> If your class doesn't yet extends any class in order to use mixins, you have to explicitly extends Object.

* Create an `async` method to initialize or open your database. You can call it during the class initialization or as a standalone method. Then, choose a name for your database. Fluttercouch stores a reference to the database by that name. If it doesn't exists yet, Fluttercouch will create one for you. It it exists, it will be set as you default database for functions you'll call from that moment.

[source, dart]
----
class MyModel extends Object with Fluttercouch {

  static const MY_DATABASE = "myDatabaseName"

  MyModel() {
    initCouchbaseLite();
  }

  initCouchbaseLite() async { # <1>
    await initDatabaseWithName(MY_DATABASE); # <2>
  }

}
----
<1> Don't initialize `Fluttercouch` directly into the class constructor, because during instantiation asynchronous call aren't allowed.
<2> Init the database with a name of your choice. From now on, it will become your default database for further operations, and you'll use that name for referencing it in some instructions.

////
=== Listening to Database Changes
MISSING FEATURE
////

=== Disposing of the Repository
When a user logs out, we close the Couchbase Lite database associated with the user, deregister any data-base change listeners, and free up memory allocations.

Open the _lib/my_model.dart_ file, and locate the `Dispose` method. Under the hood, `closeDatabase()` and `closeDatabaseWithName()` handles the removal of database listeners, removing various objects from memory, and closing the database. `Dispose` will be called after a user logs out.

[source, dart]
----
dispose() async {
  await closeDatabase(); # <1>
  // await closeDatabaseWithName(MY_DATABASE);
}
----

<1> Because we have only one registered database in our application, and after initialization is selected as default, we can simly call `closeDatabase()`. The two methods are identical, but you would prefer `closeDatabaseWithName()` if you have different databases.

=== Try it out

* The app can be tested using a simulator/emulator or device.
* Log into the app with any username and password. Let's use the values _"demo@example.com"_ and _"password"_ for username and password fields respectively. If this is the first time that the user sign-in, a new Couchbase Lite database will be created. If not, the user's existing database will be opened.

=== Confirmation of Results (iOS)

* Confirm that the console log output has a message similar to the one below. In my example, I am logging in with a username of _"demo@example.com"_.
* The above log message indicates the location of the database for the user.
* Open the folder in your Finder app and verify that a dabase with name _"userprofile"_ exists for the user.


== Document Operations
Once a instance of the Couchbase Lite database is created/opened for the specific user, we can perform basic `Document` functions on the database. In this section, we will walkthrough the code that describes basic `Document` operations.

=== Reading a Document
Once the user logs in, the user is taken to the "Your Profile" screen. A request is made to load The "User Profile" Document for the user. When the user logs in the very first time, there would be no _user profile_ document for the user.

* Open the _lib/my_model.dart_ file and locate the `userProfileDocId` definition. This document Id is constructed by prefixing the term "user::" to the name of the user.
* The `UserProfileViewModel` is tasked with retrieving the profile for a logged in user. 
* We try to fetch the document with specified `userProfileDocId` from the database.

[source, dart]
----
    Document document = await getDocumentWithId(userProfileDocId);

    if (document.isNotNull()) {
      var userProfile = new UserProfile(
        id: document.id,
        name: document.getString("name"),
        email: document.getString("email"),
        address: document.getString("address"),
      );
    }
----

<1> Fetch an *immutable* copy of the `Document` from the database.
<2> Create an instance of the UserProfile class.
<3> Set the `email` property of the UserProfile with the username of the logged in user. *Note*: This value is not editable after it's initially saved.
<4> If the document exists and is fetched successfully, a variety of methods exist that can be used to fetch members of the `Document`. Some examples are `getString` and `getFloat`.

=== Creating / Updating a Document
A The "User Profile" Document is created for the user when the user taps the "Done" button of the "Profile Screen" The function below applies whether you are creating a document or updating an existing version.

* The `UserProfileViewModel` is tasked with setting values of a profile for a logged in user, and saving them to the database. It does this calling the toDocument() member of the class UserProfile.

[source, dart]
----
bool success = saveDocument(userProfile.toDocument());
----

* Open the _lib/user_profile.dart_ file and locate the `toDocument` function.

[source, dart]
----
public Document toDocument();
----

* We create a new *mutable* `Document`. By default, all APIs in Couchbase Lite deal with immutable objects, thereby making them *thread-safe* by desing. In order to mutate an object, you must explicitly get a mutable copy of the object. Use appropriate type-setters to set the various properties of the `Document`

[source, dart]
----
MutableDocument mutableDocument = new MutableDocument(this.id);
mutableDocument.setString("name", this.name);
mutableDocument.setString("email", this.email);
mutableDocument.setString("address", this.address);

return mutableDocument;
----

=== Deleting a Document
We don't delete a `Document` in this simple app. However, deletion of a document is pretty straightforward and this is how you would do it.

[source, dart]
----
Document document = getDocumentWithId(id);

if (document.isNotNull()) {
  document.delete();
}
----

=== Try it out
* You should have followed the steps discussed in the "Try it out" section under Create / Open a Database
* Enter a "name" for the user in the TextView and Tap "Done".
* Confirm that you see an alert message "Successfully Updated Profile". The first time you update the profile screen, the Document will be created.
* Now tap on the "Upload Image" button and select an image from the Photo Album. Tap "Done".
* Confirm that you see an alert message "Successfully Updated Profile". The Document will be updated this time.
* Tap "Log Off" and log out of the app.
* Log back into the app with the same user email Id and password that you used earlier. In my example, I used _"demo@example.com"_ and _"password"_. So I will log in with those credentials again.
* Confirm that you see the profile screen with the _name_ and _image_ values that you set earlier.

== Learn More
Congratulations on completing this tutorial!

This tutorial walked you through a very basic example of how to get up and running with Couchbase Lite as a local-only, standalone embedded data store in your Flutter app, running on Android and iOS. If you want to learn more about Couchbase Mobile 2.x, check out the following links.

=== Further Reading
* link:https://www.couchbase.com/products/mobile[Introduction to Couchbase Mobile]
* link:https://blog.couchbase.com/couchbase-mobile-2-0/[Couchbase Mobile 2.0 Overview]
* link:https://developer.couchbase.com/documentation/mobile/2.0/couchbase-lite/index.html[Couchbase Lite Reference Guide]
* link:https://blog.couchbase.com/category/couchbase-mobile/[Couchbase Mobile Blog]
